import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/components/header";
const inter =Inter({
  subsets: ["latin"],

});
import {
  ClerkProvider,

} from '@clerk/nextjs'
export const metadata = {
  title: "CalistheniX",
  description: "Generated by create next app",
  icons:{
    icon:'/favicon.png'
  }
};

export default function RootLayout({ children }) {
  return (
    <ClerkProvider>
    <html lang="en">
      <body
        className={`${inter.className} `}>
        {/* Header */}
        <Header />
     <main className="min-h-screen">
     {children}
     </main>
        {/* Footer */}
        <footer className="bg-blue-50 text-white py-4">
          <div className="container mx-auto text-center text-gray-600">
            <p>&copy; 2025 Calisthenix. Made By Team <strong>CodeX</strong> .</p>
          </div>
        </footer>
      </body>
    </html>
    </ClerkProvider>
  );
}
